docker: run scons with correct env. run qserv-start

diff --git a/devops/qserv/Dockerfile b/devops/qserv/Dockerfile
--- a/devops/qserv/Dockerfile
+++ b/devops/qserv/Dockerfile
@@ -42,11 +42,11 @@ RUN cd ${BUILDROOT} && \
     ./newinstall-qserv-${QSERV_VERSION}.sh -H $INSTALL_BASE/qserv
 
 ## configure qserv
-RUN . ${INSTALL_BASE}/qserv/setup-qserv.sh
-RUN cd $INSTALL_BASE/qserv/stack/Linux64/qserv/${QSERV_VERSION}/admin && \
-    scons
+RUN . ${INSTALL_BASE}/qserv/setup-qserv.sh && \
+    cd $INSTALL_BASE/qserv/stack/Linux64/qserv/${QSERV_VERSION}/admin && \
+    scons || echo "fail"
 
 ## clean-up
 RUN /bin/rm -rf /build/lsst
 
-WORKDIR /opt/lsst-sw/qserv
+CMD ["qserv-start.sh"]
